[functions.steam-callback]
verify_jwt = false

[functions.plugin-link-start]
verify_jwt = false

[functions.plugin-link-status]
verify_jwt = false

[functions.plugin-link-unlink]
verify_jwt = false

[functions.plugin-link-complete]
verify_jwt = false

[functions.plugin-link-remove]
verify_jwt = false

[functions.plugin-links-list]
verify_jwt = false

[functions.user-system-upload]
verify_jwt = false

[functions.protondb-summary]
verify_jwt = false

[functions.steam-appdetails]
verify_jwt = false

[functions.steam-depot-info]
verify_jwt = false

[functions.image-refetch]
verify_jwt = false

[functions.steam-explore]
verify_jwt = false
