// Single loader for all Steam header images.
// All pages and components must route through loadSteamImg / window.__steamImgLoad.
// Fallback chain: akamai (primary, set as img src) -> cloudflare CDN -> game-images.json hash URL -> hidden placeholder.

const _CDN2 = id => `https://cdn.cloudflare.steamstatic.com/steam/apps/${id}/header.jpg`;

const _USES_PROD_DATA = ['localhost', '127.0.0.1', '0.0.0.0'].includes(window.location.hostname)
  || (window.location.hostname || '').endsWith('.github.io');

const _GAME_IMAGES_URL = _USES_PROD_DATA
  ? 'https://www.proton-pulse.com/game-images.json'
  : 'game-images.json';

// Cover images for non-Steam (GOG/Epic) games, keyed by canonical id
// (gog:<productId>, epic:<namespace>). Generated by the pipeline from the store
// catalog APIs. Steam ids never appear here.
const _NONSTEAM_IMAGES_URL = _USES_PROD_DATA
  ? 'https://www.proton-pulse.com/nonsteam-images.json'
  : 'nonsteam-images.json';

let _gameImagesPromise = null;
function _loadGameImages() {
  if (!_gameImagesPromise) {
    _gameImagesPromise = fetch(_GAME_IMAGES_URL)
      .then(r => r.ok ? r.json() : {})
      .catch(() => ({}));
  }
  return _gameImagesPromise;
}

let _nonsteamImagesPromise = null;
function _loadNonsteamImages() {
  if (!_nonsteamImagesPromise) {
    _nonsteamImagesPromise = fetch(_NONSTEAM_IMAGES_URL)
      .then(r => r.ok ? r.json() : {})
      .catch(() => ({}));
  }
  return _nonsteamImagesPromise;
}

function _tryUrl(url) {
  return new Promise(resolve => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = () => resolve(null);
    img.src = url;
  });
}

function _swap(el, loaded) {
  loaded.className = el.className;
  loaded.alt = el.alt || '';
  el.parentNode?.replaceChild(loaded, el);
}

// Session-scoped route counters surfaced on the admin analytics page.
// Each fallback hit increments one bucket. Primary akamai successes are NOT
// counted here -- onerror does not fire on success, and we do not instrument
// every img tag. The admin can read totals separately and subtract.
function _bumpRoute(route) {
  const counts = window.__imgRouteCounts || (window.__imgRouteCounts = {
    cloudflare: 0,
    'game-images-json': 0,
    'nonsteam-images-json': 0,
    hidden: 0,
  });
  counts[route] = (counts[route] || 0) + 1;
}

// Called after the primary akamai src fails (onerror).
// Tries cloudflare, then game-images.json, then hides the slot.
export async function loadSteamImg(el, appId) {
  const id = String(appId);

  // Non-Steam (GOG/Epic) games have no Steam CDN image. Resolve their cover
  // straight from the pipeline's nonsteam-images.json instead of walking the
  // Steam CDN chain (which would always 404 for a prefixed id).
  if (id.startsWith('gog:') || id.startsWith('epic:')) {
    const nsMap = await _loadNonsteamImages();
    const nsUrl = nsMap[id];
    if (nsUrl) {
      const loaded = await _tryUrl(nsUrl);
      if (loaded) {
        console.log(`[steam-img] appId=${id} route=nonsteam-images-json`);
        _bumpRoute('nonsteam-images-json');
        _swap(el, loaded);
        return;
      }
    }
    console.warn(`[steam-img] appId=${id} no non-Steam cover available`);
    _bumpRoute('hidden');
    el.style.visibility = 'hidden';
    return;
  }

  const cdn2 = await _tryUrl(_CDN2(id));
  if (cdn2) {
    console.log(`[steam-img] appId=${id} route=cloudflare`);
    _bumpRoute('cloudflare');
    _swap(el, cdn2);
    return;
  }

  const map = await _loadGameImages();
  const url = map[id];
  if (url) {
    const loaded = await _tryUrl(url);
    if (loaded) {
      console.log(`[steam-img] appId=${id} route=game-images-json`);
      _bumpRoute('game-images-json');
      _swap(el, loaded);
      return;
    }
  }

  console.warn(`[steam-img] appId=${id} all CDN paths exhausted`);
  _bumpRoute('hidden');
  el.style.visibility = 'hidden';
}

// Global bridge for inline onerror="window.__steamImgLoad(this)".
// img elements must carry data-appid="${appId}".
window.__steamImgLoad = el => {
  const appId = el.dataset.appid;
  if (appId) loadSteamImg(el, appId);
  else el.style.visibility = 'hidden';
};
